name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  hosting:
    name: Deploy to Firebase Hosting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set npm registry
        run: npm config set registry https://registry.npmjs.org/

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install Firebase CLI
        run: npm install -g firebase-tools@12.4.0

      - name: Check npm and Firebase CLI
        run: |
          npm --version
          node --version
          firebase --version

      - name: Build Flutter Web
        run: |
          flutter config --enable-web
          flutter pub get
          flutter build web --web-renderer canvaskit --release
        working-directory: ./

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --project card-cambio
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
